# Welcome to Agency Jekyll Theme!

# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings

title: The Halanych Lab
email: ken@auburn.edu
description: > # this means to ignore newlines until "author:"
  The Halanych Lab at Auburn University.
#author: laklau
#keyword: jekyll
#baseurl: "" # the subpath of your site, e.g. /blog
url: http://DamienWaits.github.io # the base hostname & protocol for your site, e.g. http://example.com
#github_username:  laklau

# Build settings

markdown: kramdown

#theme: agency-jekyll-theme #The "agency-jekyll-theme" is not supported by GitHub Pages. 

gems:
  - jekyll-feed
exclude:
  - agency-jekyll-theme.gemspec
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - screenshot.png
